"use client";

import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { RandomFox } from "../components/RandomFox";
import { useState } from "react";

function generateRandomNumber(): number {
  return Math.floor(Math.random() * 123) + 1;
}

function generateRandomUUID(): string {
  return Math.random().toString(36).substr(2, 9);
}

type ImageTypeProps = { id: string; url: string };

const Home: NextPage = () => {
  const [imagesUrls, setimagesUrls] = useState<Array<ImageTypeProps>>([
    {
      id: generateRandomUUID(),
      url: `https://randomfox.ca/images/${generateRandomNumber()}.jpg`,
    },
    {
      id: generateRandomUUID(),
      url: `https://randomfox.ca/images/${generateRandomNumber()}.jpg`,
    },
    {
      id: generateRandomUUID(),
      url: `https://randomfox.ca/images/${generateRandomNumber()}.jpg`,
    },
    {
      id: generateRandomUUID(),
      url: `https://randomfox.ca/images/${generateRandomNumber()}.jpg`,
    },
  ]);

function addFoxImage() {
    const newImage = {
      id: generateRandomUUID(),
      url: generateRandomNumber(),
    };

    setimagesUrls([...imagesUrls, newImage]);
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">Hola mundo!</h1>
        {imagesUrls.map(({ id, url }) => (
          <div key={id}>
            <RandomFox imageUrl={url} />
          </div>
        ))}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
