"use client";

import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { LazyImage } from "../components/LazyImage";
import type { MouseEvent } from "react";
import { useCallback, useState } from "react";

function generateRandomNumber(): number {
  return Math.floor(Math.random() * 123) + 1;
}

function generateRandomUUID(): string {
  return Math.random().toString(36).substr(2, 9);
}

type Imagetype = { id: string; src: string };

const Home: NextPage = () => {
  const [imagesUrls, setimagesUrls] = useState<Array<Imagetype>>([]);

  function addFoxImage(event: MouseEvent<HTMLButtonElement>): void {
    const newImage = {
      id: generateRandomUUID(),
      src: `https://randomfox.ca/images/${generateRandomNumber()}.jpg`,
    };

    setimagesUrls([...imagesUrls, newImage]);
  }

  const onLazyFunction = useCallback(() => {
    console.log("AUU");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">Hola mundo!</h1>
        <button onClick={addFoxImage}>Agregar Imagen</button>
        {imagesUrls.map(({ id, src }) => (
          <div key={id}>
            <LazyImage
              srcProp={src}
              onClick={() => console.log("Hey")}
              onLazyLoading={() => onLazyFunction()}
            />
          </div>
        ))}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
